name: Heroku Build Logs
on: deployment_status

jobs:
  heroku-build-logs:
    name: Heroku Build Logs
    runs-on: ubuntu-latest
    steps:
      - name: Heroku Build Logs
        uses: ctc-uci/github-action-heroku-logs@testing
        env:
          GITHUB_TOKEN: ${{ secrets.CTC_DEVOPS_BOT_PAT }}
          DEVOPS_PAT_TOKEN: ${{ secrets.CTC_DEVOPS_BOT_PAT }}
          HEROKU_AUTH_TOKEN: ${{ secrets.CTC_HEROKU_API_KEY }}
